---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/deenafink/Desktop/Github/deenaFinalProject/project'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x100000980, symSize: 0x40 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x100000980, symSize: 0x40 }
  - { offsetInCU: 0x85, offset: 0x85, size: 0x8, addend: 0x0, symName: _store_numbers, symObjAddr: 0x40, symBinAddr: 0x1000009C0, symSize: 0xA0 }
  - { offsetInCU: 0xE1, offset: 0xE1, size: 0x8, addend: 0x0, symName: _print_d, symObjAddr: 0xE0, symBinAddr: 0x100000A60, symSize: 0x2E0 }
  - { offsetInCU: 0x2B3, offset: 0x2B3, size: 0x8, addend: 0x0, symName: _print_c, symObjAddr: 0x3C0, symBinAddr: 0x100000D40, symSize: 0xB0 }
  - { offsetInCU: 0x355, offset: 0x355, size: 0x8, addend: 0x0, symName: _print_s, symObjAddr: 0x470, symBinAddr: 0x100000DF0, symSize: 0x2E0 }
  - { offsetInCU: 0x4F8, offset: 0x4F8, size: 0x8, addend: 0x0, symName: _print_x, symObjAddr: 0x750, symBinAddr: 0x1000010D0, symSize: 0x300 }
  - { offsetInCU: 0x703, offset: 0x703, size: 0x8, addend: 0x0, symName: _print_m, symObjAddr: 0xA50, symBinAddr: 0x1000013D0, symSize: 0x220 }
  - { offsetInCU: 0x7EE, offset: 0x7EE, size: 0x8, addend: 0x0, symName: _print_b, symObjAddr: 0xC70, symBinAddr: 0x1000015F0, symSize: 0x1D0 }
  - { offsetInCU: 0x944, offset: 0x944, size: 0x8, addend: 0x0, symName: _my_printf, symObjAddr: 0xE40, symBinAddr: 0x1000017C0, symSize: 0x780 }
  - { offsetInCU: 0xA96, offset: 0xA96, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x15C0, symBinAddr: 0x100001F40, symSize: 0x3D }
...
