---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/deenafink/Desktop/Github/deenaFinalProject/project'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x1000007E0, symSize: 0x40 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x1000007E0, symSize: 0x40 }
  - { offsetInCU: 0x85, offset: 0x85, size: 0x8, addend: 0x0, symName: _store_numbers, symObjAddr: 0x40, symBinAddr: 0x100000820, symSize: 0xA0 }
  - { offsetInCU: 0xE1, offset: 0xE1, size: 0x8, addend: 0x0, symName: _print_d, symObjAddr: 0xE0, symBinAddr: 0x1000008C0, symSize: 0x2E0 }
  - { offsetInCU: 0x2B3, offset: 0x2B3, size: 0x8, addend: 0x0, symName: _print_c, symObjAddr: 0x3C0, symBinAddr: 0x100000BA0, symSize: 0xB0 }
  - { offsetInCU: 0x355, offset: 0x355, size: 0x8, addend: 0x0, symName: _print_s, symObjAddr: 0x470, symBinAddr: 0x100000C50, symSize: 0x2E0 }
  - { offsetInCU: 0x4F8, offset: 0x4F8, size: 0x8, addend: 0x0, symName: _print_x, symObjAddr: 0x750, symBinAddr: 0x100000F30, symSize: 0x300 }
  - { offsetInCU: 0x704, offset: 0x704, size: 0x8, addend: 0x0, symName: _print_m, symObjAddr: 0xA50, symBinAddr: 0x100001230, symSize: 0x220 }
  - { offsetInCU: 0x7EF, offset: 0x7EF, size: 0x8, addend: 0x0, symName: _print_b, symObjAddr: 0xC70, symBinAddr: 0x100001450, symSize: 0x1F0 }
  - { offsetInCU: 0x945, offset: 0x945, size: 0x8, addend: 0x0, symName: _print_l, symObjAddr: 0xE60, symBinAddr: 0x100001640, symSize: 0xC0 }
  - { offsetInCU: 0x9B5, offset: 0x9B5, size: 0x8, addend: 0x0, symName: _my_printf, symObjAddr: 0xF20, symBinAddr: 0x100001700, symSize: 0x810 }
  - { offsetInCU: 0xB25, offset: 0xB25, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x1730, symBinAddr: 0x100001F10, symSize: 0x73 }
...
