---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/deenafink/Desktop/Github/deenaFinalProject/project'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100000F50, symSize: 0x33 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100000F50, symSize: 0x33 }
...
