---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/deenafink/Desktop/Github/deenaFinalProject/project'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x100000600, symSize: 0x40 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x100000600, symSize: 0x40 }
  - { offsetInCU: 0x85, offset: 0x85, size: 0x8, addend: 0x0, symName: _store_numbers, symObjAddr: 0x40, symBinAddr: 0x100000640, symSize: 0xA0 }
  - { offsetInCU: 0xE1, offset: 0xE1, size: 0x8, addend: 0x0, symName: _print_d, symObjAddr: 0xE0, symBinAddr: 0x1000006E0, symSize: 0x370 }
  - { offsetInCU: 0x2C1, offset: 0x2C1, size: 0x8, addend: 0x0, symName: _print_c, symObjAddr: 0x450, symBinAddr: 0x100000A50, symSize: 0xB0 }
  - { offsetInCU: 0x363, offset: 0x363, size: 0x8, addend: 0x0, symName: _print_s, symObjAddr: 0x500, symBinAddr: 0x100000B00, symSize: 0x2E0 }
  - { offsetInCU: 0x506, offset: 0x506, size: 0x8, addend: 0x0, symName: _print_x, symObjAddr: 0x7E0, symBinAddr: 0x100000DE0, symSize: 0x300 }
  - { offsetInCU: 0x713, offset: 0x713, size: 0x8, addend: 0x0, symName: _print_m, symObjAddr: 0xAE0, symBinAddr: 0x1000010E0, symSize: 0x220 }
  - { offsetInCU: 0x7FE, offset: 0x7FE, size: 0x8, addend: 0x0, symName: _print_b, symObjAddr: 0xD00, symBinAddr: 0x100001300, symSize: 0x1F0 }
  - { offsetInCU: 0x954, offset: 0x954, size: 0x8, addend: 0x0, symName: _print_l, symObjAddr: 0xEF0, symBinAddr: 0x1000014F0, symSize: 0xC0 }
  - { offsetInCU: 0x9C4, offset: 0x9C4, size: 0x8, addend: 0x0, symName: _my_printf, symObjAddr: 0xFB0, symBinAddr: 0x1000015B0, symSize: 0x840 }
  - { offsetInCU: 0xB44, offset: 0xB44, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x17F0, symBinAddr: 0x100001DF0, symSize: 0x12D }
...
