---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/deenafink/Desktop/Github/deenaFinalProject/project'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x1000006C0, symSize: 0x40 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x1000006C0, symSize: 0x40 }
  - { offsetInCU: 0x85, offset: 0x85, size: 0x8, addend: 0x0, symName: _handle_error, symObjAddr: 0x40, symBinAddr: 0x100000700, symSize: 0x50 }
  - { offsetInCU: 0xA9, offset: 0xA9, size: 0x8, addend: 0x0, symName: _store_numbers, symObjAddr: 0x90, symBinAddr: 0x100000750, symSize: 0xA0 }
  - { offsetInCU: 0x105, offset: 0x105, size: 0x8, addend: 0x0, symName: _print_d, symObjAddr: 0x130, symBinAddr: 0x1000007F0, symSize: 0x370 }
  - { offsetInCU: 0x2E5, offset: 0x2E5, size: 0x8, addend: 0x0, symName: _print_c, symObjAddr: 0x4A0, symBinAddr: 0x100000B60, symSize: 0xA0 }
  - { offsetInCU: 0x35D, offset: 0x35D, size: 0x8, addend: 0x0, symName: _print_s, symObjAddr: 0x540, symBinAddr: 0x100000C00, symSize: 0x2D0 }
  - { offsetInCU: 0x4E2, offset: 0x4E2, size: 0x8, addend: 0x0, symName: _print_x, symObjAddr: 0x810, symBinAddr: 0x100000ED0, symSize: 0x300 }
  - { offsetInCU: 0x6F1, offset: 0x6F1, size: 0x8, addend: 0x0, symName: _print_m, symObjAddr: 0xB10, symBinAddr: 0x1000011D0, symSize: 0x270 }
  - { offsetInCU: 0x792, offset: 0x792, size: 0x8, addend: 0x0, symName: _print_b, symObjAddr: 0xD80, symBinAddr: 0x100001440, symSize: 0x1E0 }
  - { offsetInCU: 0x898, offset: 0x898, size: 0x8, addend: 0x0, symName: _print_l, symObjAddr: 0xF60, symBinAddr: 0x100001620, symSize: 0xC0 }
  - { offsetInCU: 0x908, offset: 0x908, size: 0x8, addend: 0x0, symName: _my_printf, symObjAddr: 0x1020, symBinAddr: 0x1000016E0, symSize: 0x800 }
  - { offsetInCU: 0xA88, offset: 0xA88, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x1820, symBinAddr: 0x100001EE0, symSize: 0x6E }
...
