---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/deenafink/Desktop/Github/deenaFinalProject/project'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x1000006F0, symSize: 0x40 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _get_sign, symObjAddr: 0x0, symBinAddr: 0x1000006F0, symSize: 0x40 }
  - { offsetInCU: 0x85, offset: 0x85, size: 0x8, addend: 0x0, symName: _store_numbers, symObjAddr: 0x40, symBinAddr: 0x100000730, symSize: 0xA0 }
  - { offsetInCU: 0xE1, offset: 0xE1, size: 0x8, addend: 0x0, symName: _print_d, symObjAddr: 0xE0, symBinAddr: 0x1000007D0, symSize: 0x370 }
  - { offsetInCU: 0x2C1, offset: 0x2C1, size: 0x8, addend: 0x0, symName: _print_c, symObjAddr: 0x450, symBinAddr: 0x100000B40, symSize: 0xA0 }
  - { offsetInCU: 0x339, offset: 0x339, size: 0x8, addend: 0x0, symName: _print_s, symObjAddr: 0x4F0, symBinAddr: 0x100000BE0, symSize: 0x300 }
  - { offsetInCU: 0x4CC, offset: 0x4CC, size: 0x8, addend: 0x0, symName: _print_x, symObjAddr: 0x7F0, symBinAddr: 0x100000EE0, symSize: 0x300 }
  - { offsetInCU: 0x6DA, offset: 0x6DA, size: 0x8, addend: 0x0, symName: _print_m, symObjAddr: 0xAF0, symBinAddr: 0x1000011E0, symSize: 0x220 }
  - { offsetInCU: 0x7C5, offset: 0x7C5, size: 0x8, addend: 0x0, symName: _print_b, symObjAddr: 0xD10, symBinAddr: 0x100001400, symSize: 0x1F0 }
  - { offsetInCU: 0x91B, offset: 0x91B, size: 0x8, addend: 0x0, symName: _print_l, symObjAddr: 0xF00, symBinAddr: 0x1000015F0, symSize: 0xC0 }
  - { offsetInCU: 0x98B, offset: 0x98B, size: 0x8, addend: 0x0, symName: _my_printf, symObjAddr: 0xFC0, symBinAddr: 0x1000016B0, symSize: 0x830 }
  - { offsetInCU: 0xB0B, offset: 0xB0B, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x17F0, symBinAddr: 0x100001EE0, symSize: 0x5D }
...
